project:
  version: "@project.version@"

# mariaDB related configurations
spring:
  datasource:
    url: jdbc:mariadb://sgiam_kata_db:3306/sgiam_kata
    username: sgiam_kata_user
    password: s3ZU(Jf6J3ocjLW
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

#openapi related configurations
springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /v1/swagger-ui.html
    operationsSorter: method

#https related configurations
server:
  http:
    interface: 0.0.0.0
    port: 8080
  port: 8443
  ssl:
    key-store: classpath:sgiam_kata.p12
    key-store-password: sgiam_kata
    keyStoreType: PKCS12